# Claude Code for GitHub 設定
# このファイルはGitHub上でのClaude使用を制御します

# 使用するモデルを制限
# sonnet は使用しない - opus のみ許可
model:
  # 許可するモデル
  allowed:
    - claude-opus-4-5-20251101
    - opus
  # 禁止するモデル（明示的に拒否）
  denied:
    - sonnet
    - claude-3-sonnet
    - claude-3-5-sonnet
    - claude-sonnet-4-20250514
    - claude-4-sonnet

# Pull Request レビュー設定
pull_request:
  # PRレビューで使用するモデル
  model: opus
  # 自動レビューを有効にするか
  auto_review: true

# コードレビュー設定
code_review:
  model: opus
